#!/bin/bash
TINCIV=6.0.1

HOOK="$(pwd)/hooks/tinci"
PREHOOK="$(pwd)/hooks/tinci-pre"
LOGDIR="$(pwd)/.tinci"
mkdir -p "$LOGDIR"

TDIR=$(mktemp -d "${TMPDIR:-/tmp}"/tinci.XXXXXXXX)
mkdir -p $TDIR
trap "trap - EXIT; rm -rf $TDIR" EXIT

while read OLDSHA NEWSHA REF ; do

  [ "$NEWSHA" != "0000000000000000000000000000000000000000" ] || continue

  CMD="$(git archive $NEWSHA | tar -t | grep '^.tinci$')"
  [ "$CMD" ] || continue

  INPUT="$OLDSHA $NEWSHA $REF"
  LOGFILE="$LOGDIR/$NEWSHA.log"
  PLOGFILE="$LOGDIR/$OLDSHA.log"
  WDIR=$TDIR/$NEWSHA
  mkdir -p $WDIR

  [ -f $PLOGFILE ] && PSTAT=$(tail -n1 $PLOGFILE 2>/dev/null | sed -nE 's/^# code ([0-9]+)$/\1/p')
  [ ! "$PSTAT" ] && PSTAT=0

  git archive $NEWSHA | tar -x -C $WDIR
  ( cd $WDIR
    [ -x "$PREHOOK" ] && echo $INPUT | sh "$PREHOOK" $PSTAT 2>&1

    echo -e "# tinci $TINCIV\n# ref $REF\n# running sh $CMD" | tee "$LOGFILE"
    ( sh "$CMD" 2>&1; echo "# code $?" ) | tee -a "$LOGFILE"
    STAT=$(tail -n1 "$LOGFILE" | sed -nE 's/^# code ([0-9]+)$/\1/p')

    [ -x "$HOOK" ] && echo $INPUT | sh "$HOOK" "$STAT" 2>&1
  )

  if [ $STAT -eq 0 ]; then
    [ $PSTAT -eq 0 ] && echo -e "\nJob successful!" || echo -e "\nJob fixed!"
  else
    [ $PSTAT -eq 0 ] && echo -e >&2 "\nJob failed!" || echo -e >&2 "\nJob is still failing!"
  fi
done
